"""empty message

Revision ID: 3e09d3e8d6aa
Revises: 856ee20cf444
Create Date: 2018-05-18 00:19:36.706334

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3e09d3e8d6aa'
down_revision = '856ee20cf444'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('continents', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('countries', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('dest_locations', 'lat',
               existing_type=sa.NUMERIC(precision=10, scale=8),
               nullable=True)
    op.alter_column('dest_locations', 'lng',
               existing_type=sa.NUMERIC(precision=11, scale=8),
               nullable=True)
    op.alter_column('dest_tags', 'dest_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('dest_tags', 'tag_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('destinations', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('destinations', 'update_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('explored', 'dest_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('explored', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('favorites', 'dest_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('favorites', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('regions', 'cont_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('regions', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('tags', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.add_column('users', sa.Column('first_name', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_users_time_created'), 'users', ['time_created'], unique=False)
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.drop_index(op.f('ix_users_time_created'), table_name='users')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.alter_column('tags', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('regions', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('regions', 'cont_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('favorites', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('favorites', 'dest_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('explored', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('explored', 'dest_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('destinations', 'update_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('destinations', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('dest_tags', 'tag_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('dest_tags', 'dest_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('dest_locations', 'lng',
               existing_type=sa.NUMERIC(precision=11, scale=8),
               nullable=False)
    op.alter_column('dest_locations', 'lat',
               existing_type=sa.NUMERIC(precision=10, scale=8),
               nullable=False)
    op.alter_column('countries', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('continents', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###
