"""fixed some stuff in models.py

Revision ID: 5ce60da02b47
Revises: 9d6d5f2deb1a
Create Date: 2018-05-16 17:39:17.335837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ce60da02b47'
down_revision = '9d6d5f2deb1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_destinations_update_date'), 'destinations', ['update_date'], unique=False)
    op.create_index(op.f('ix_users_time_created'), 'users', ['time_created'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_time_created'), table_name='users')
    op.drop_index(op.f('ix_destinations_update_date'), table_name='destinations')
    # ### end Alembic commands ###
