"""empty message

Revision ID: 856ee20cf444
Revises: fd4acd7ec5e5
Create Date: 2018-05-17 13:03:46.619825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '856ee20cf444'
down_revision = 'fd4acd7ec5e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('dest_tags_tag_id_fkey', 'dest_tags', type_='foreignkey')
    op.drop_constraint('dest_tags_dest_id_fkey', 'dest_tags', type_='foreignkey')
    op.create_foreign_key(None, 'dest_tags', 'destinations', ['dest_id'], ['dest_id'])
    op.create_foreign_key(None, 'dest_tags', 'tags', ['tag_id'], ['tag_id'])
    op.drop_constraint('explored_dest_id_fkey', 'explored', type_='foreignkey')
    op.drop_constraint('explored_user_id_fkey', 'explored', type_='foreignkey')
    op.create_foreign_key(None, 'explored', 'destinations', ['dest_id'], ['dest_id'])
    op.create_foreign_key(None, 'explored', 'users', ['user_id'], ['user_id'])
    op.drop_constraint('favorites_user_id_fkey', 'favorites', type_='foreignkey')
    op.drop_constraint('favorites_dest_id_fkey', 'favorites', type_='foreignkey')
    op.create_foreign_key(None, 'favorites', 'users', ['user_id'], ['user_id'])
    op.create_foreign_key(None, 'favorites', 'destinations', ['dest_id'], ['dest_id'])
    op.alter_column('regions', 'cont_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('regions', 'cont_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'favorites', type_='foreignkey')
    op.drop_constraint(None, 'favorites', type_='foreignkey')
    op.create_foreign_key('favorites_dest_id_fkey', 'favorites', 'destinations', ['dest_id'], ['dest_id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('favorites_user_id_fkey', 'favorites', 'users', ['user_id'], ['user_id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(None, 'explored', type_='foreignkey')
    op.drop_constraint(None, 'explored', type_='foreignkey')
    op.create_foreign_key('explored_user_id_fkey', 'explored', 'users', ['user_id'], ['user_id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('explored_dest_id_fkey', 'explored', 'destinations', ['dest_id'], ['dest_id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(None, 'dest_tags', type_='foreignkey')
    op.drop_constraint(None, 'dest_tags', type_='foreignkey')
    op.create_foreign_key('dest_tags_dest_id_fkey', 'dest_tags', 'destinations', ['dest_id'], ['dest_id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('dest_tags_tag_id_fkey', 'dest_tags', 'tags', ['tag_id'], ['tag_id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###
