"""empty message

Revision ID: 9d6d5f2deb1a
Revises: 4008c71e3279
Create Date: 2018-05-08 02:06:16.652374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d6d5f2deb1a'
down_revision = '4008c71e3279'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('continents',
    sa.Column('cont_id', sa.Integer(), nullable=False),
    sa.Column('cont_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('cont_id'),
    sa.UniqueConstraint('cont_name')
    )
    op.create_table('tags',
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('tag_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('tag_id')
    )
    op.create_table('regions',
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('cont_id', sa.Integer(), nullable=True),
    sa.Column('region_name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['cont_id'], ['continents.cont_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('region_id'),
    sa.UniqueConstraint('region_name')
    )
    op.create_table('countries',
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('country_name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions.region_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('country_id'),
    sa.UniqueConstraint('country_name')
    )
    op.create_table('destinations',
    sa.Column('dest_id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.Column('dest_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('update_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.country_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dest_id'),
    sa.UniqueConstraint('dest_name')
    )
    op.create_table('dest_images',
    sa.Column('dest_id', sa.Integer(), nullable=False),
    sa.Column('img_url', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['dest_id'], ['destinations.dest_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dest_id', 'img_url')
    )
    op.create_table('dest_locations',
    sa.Column('dest_id', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Numeric(precision=10, scale=8), nullable=False),
    sa.Column('lng', sa.Numeric(precision=11, scale=8), nullable=False),
    sa.ForeignKeyConstraint(['dest_id'], ['destinations.dest_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dest_id')
    )
    op.create_table('dest_tags',
    sa.Column('dest_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dest_id'], ['destinations.dest_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.tag_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dest_id', 'tag_id')
    )
    op.create_table('explored',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('dest_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dest_id'], ['destinations.dest_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'dest_id')
    )
    op.create_table('favorites',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('dest_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dest_id'], ['destinations.dest_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'dest_id')
    )
    op.add_column('users', sa.Column('password_hash', sa.String(length=100), nullable=False))
    op.add_column('users', sa.Column('username', sa.String(length=64), nullable=True))
    op.create_unique_constraint(None, 'users', ['username'])
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'username')
    op.drop_column('users', 'password_hash')
    op.drop_table('favorites')
    op.drop_table('explored')
    op.drop_table('dest_tags')
    op.drop_table('dest_locations')
    op.drop_table('dest_images')
    op.drop_table('destinations')
    op.drop_table('countries')
    op.drop_table('regions')
    op.drop_table('tags')
    op.drop_table('continents')
    # ### end Alembic commands ###
