"""deleted country codes table and added col to country

Revision ID: e8fb8a8385b5
Revises: 0fc36eff189a
Create Date: 2018-08-10 00:54:14.421084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8fb8a8385b5'
down_revision = '0fc36eff189a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('countries', sa.Column('country_code', sa.String(length=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dest_images', 'img_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('countries', 'code')
    op.create_table('country_codes',
    sa.Column('country_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('country_code', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], name='country_codes_country_id_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('country_id', name='country_codes_pkey')
    )
    # ### end Alembic commands ###
